#Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/db_animalproduction
spring.datasource.username=postgres
spring.datasource.password=Kigali@10
spring.datasource.driver-class-name=org.postgresql.Driver

#JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

#Server Configuration
server.port=8888
server.servlet.context-path=/

#Multipart File Upload Configuration
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
spring.servlet.multipart.enabled=true

#Tomcat Configuration for Large Uploads
server.tomcat.max-http-post-size=52428800

#Logging Configuration (Optional)
logging.level.root=INFO
logging.level.rw.animalproduct.animal.production=DEBUG
logging.level.org.springframework.security=DEBUG

spring.thymeleaf.cache=false