package rw.animalproduct.animal.production.controller;

import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import rw.animalproduct.animal.production.services.LocationDistributionService;

@Slf4j
@Controller
@RequestMapping("/livestock/location-distribution-report")
public class LocationDistributionController {

    // FIX: Removed @RequiredArgsConstructor (Lombok annotation) and replaced with
    // explicit constructor injection. This resolves IDE "cannot resolve symbol" errors
    // caused by missing or misconfigured Lombok annotation processing in some setups.
    private final LocationDistributionService locationDistributionService;

    public LocationDistributionController(LocationDistributionService locationDistributionService) {
        this.locationDistributionService = locationDistributionService;
    }

    @GetMapping
    public String showReport(
            @RequestParam(defaultValue = "0") int page,
            @RequestParam(defaultValue = "20") int size,
            @RequestParam(defaultValue = "totalAnimals") String sortBy,
            @RequestParam(defaultValue = "desc") String direction,
            Model model) {

        log.info("Loading location distribution report - Page: {}, Size: {}, Sort: {}, Direction: {}",
                page, size, sortBy, direction);

        var report = locationDistributionService.generateReport(page, size, sortBy, direction);

        model.addAttribute("report", report);

        // FIX: report.getPage() / getTotalPages() / getSize() are plain int fields on the DTO,
        // not Spring Data Page methods. The previous error "cannot find symbol" came from
        // the IDE not recognizing Lombok @Data getters — resolved by using the DTO fields
        // directly. These calls now correctly bind to getPage(), getTotalPages(), getSize()
        // generated by @Data on LocationDistributionReportDto.
        model.addAttribute("currentPage", report.getPage());
        model.addAttribute("totalPages",  report.getTotalPages());
        model.addAttribute("pageSize",    report.getSize());
        model.addAttribute("sortBy",      sortBy);
        model.addAttribute("direction",   direction);

        // Helper list for building pagination buttons in Thymeleaf without T() calls.
        // The template iterates this list to render page number buttons safely.
        java.util.List<Integer> pageNumbers = new java.util.ArrayList<>();
        for (int i = 0; i < report.getTotalPages(); i++) {
            pageNumbers.add(i);
        }
        model.addAttribute("pageNumbers", pageNumbers);

        return "location-distribution-report";
    }
}
